{% set goname = "github.com/rclone/rclone" %}
{% set version = "1.68.2" %}

{% set name = goname.split('/')[-1] %}
{% set pkg_src = ('src/'+goname).replace("/",os.sep) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://{{ goname }}/archive/v{{ version }}.tar.gz
  sha256: 6c4c1a1702633c7a8f8755a9cfb951c3ae0b7bcc2e210b92e191250b6aae2e9f

build:
  number: 0
  script:
    - go build -v -o {{ target_gobin }}{{ name }}{{ target_goexe }}

requirements:
  build:
    - {{ compiler("go") }} >=1.13

test:
  commands:
    - rclone version

about:
  home: https://rclone.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: |
    Rclone ("rsync for cloud storage") is a command line program to
    sync files and directories to and from different cloud storage providers.
  doc_url: https://rclone.org/docs/
  dev_url: https://github.com/rclone/rclone

extra:
  recipe-maintainers:
    - luizirber
