{% set goname = "github.com/rclone/rclone" %}
{% set version = "1.73.3" %}

{% set name = goname.split('/')[-1] %}
{% set pkg_src = ('src/'+goname).replace("/",os.sep) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://{{ goname }}/archive/v{{ version }}.tar.gz
  sha256: 91a2189140b90b40cf113f974f6441f22b3a21434b00f85cd2dfdc56e6eab3d6

build:
  number: 0
  script:
    - go build -v -o {{ target_gobin }}{{ name }}{{ target_goexe }}

requirements:
  build:
    - {{ compiler("go") }} >=1.13

test:
  commands:
    - rclone version

about:
  home: https://rclone.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: |
    Rclone ("rsync for cloud storage") is a command line program to
    sync files and directories to and from different cloud storage providers.
  doc_url: https://rclone.org/docs/
  dev_url: https://github.com/rclone/rclone

extra:
  recipe-maintainers:
    - luizirber
